### ISSUE TITLE
reduce size of "bucket list": how to aggregate urls to exclude query strings or similar

### ISSUE THREAD

**Issue by jesperronn** [magenta-aps/apache_log_exporter#3]
Depending on the variety of your apache access log, this endpoint will generate a LOT of data in the /metrics endpoint.

Building on the example from the README, where one path will generate:

```
# TYPE http_latency_seconds histogram
http_latency_seconds_bucket{le="0.05",method="GET",path="/media/UUID.jpg",status="206"} 8.0
http_latency_seconds_bucket{le="0.1",method="GET",path="/media/UUID.jpg",status="206"} 9.0
http_latency_seconds_bucket{le="0.25",method="GET",path="/media/UUID.jpg",status="206"} 10.0
http_latency_seconds_bucket{le="0.5",method="GET",path="/media/UUID.jpg",status="206"} 11.0
http_latency_seconds_bucket{le="1.0",method="GET",path="/media/UUID.jpg",status="206"} 11.0
http_latency_seconds_bucket{le="2.5",method="GET",path="/media/UUID.jpg",status="206"} 13.0
http_latency_seconds_bucket{le="5.0",method="GET",path="/media/UUID.jpg",status="206"} 14.0
http_latency_seconds_bucket{le="10.0",method="GET",path="/media/UUID.jpg",status="206"} 14.0
http_latency_seconds_bucket{le="+Inf",method="GET",path="/media/UUID.jpg",status="206"} 14.0
```
Now, for any endpoint where we are using querystrings we will get this amount of data for each url that is unique in the apache access log.

Is there a way in grok exporter to limit/aggregate data for instance to ignore any variations in querystrings?

(i may also want to ignore certain endpoints in my setup like /grafana or /prometheus where I dont care about latency)

**Comment by Skeen** [comment]
Hi

I think I'd do this by preprocessing the log event stream in FluentD, before shipping it off to grok_exporter.

**Comment by jesperronn** [comment]
Thanks for input Emil for your advice. I ended up aggregating in preprocessing step (I used logstash filter, but could have been in fluentd as well).
