### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Bluscream** [magenta-aps/apache_log_exporter#4]
I tried `docker pull https://github.com/magenta-aps/apache_log_exporter`

**Comment by Skeen** [comment]
This project is not maintained anymore

**Comment by Bluscream** [comment]
Whats the recommended alternative?

**Comment by Skeen** [comment]
We moved these metrics into our application metrics instead

**Comment by Bluscream** [comment]
Oh wow, thanks anyway
